CREATE TABLE USERS (
     ID BIGSERIAL PRIMARY KEY,
     USERNAME VARCHAR(255) UNIQUE,
     PASSWORD VARCHAR(255) NOT NULL,
     NAME VARCHAR(255) DEFAULT NULL,
     LASTNAME VARCHAR(255) DEFAULT NULL,
     EMAIL VARCHAR(255) UNIQUE DEFAULT NULL,
     PHONE VARCHAR(255) DEFAULT NULL
);