ALTER TABLE USERS
    ADD COLUMN ROL_ID BIGINT,
    ADD FOREIGN KEY (ROL_ID) REFERENCES ROLES(ID);

ALTER TABLE ROL_PERMISSIONS
    ADD FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID),
    ADD FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSIONS(ID);