INSERT INTO PERMISSIONS(ID, NAME, DESCRIPTION)
values (1, 'CREATE_USERS', 'CREATE_USERS'),
       (2, 'READ_USERS', 'READ_USERS'),
       (3, 'UPDATE_USERS', 'UPDATE USERS'),
       (4, 'DELETE_USERS', 'DELETE USERS');
