INSERT INTO PERMISSIONS(ID, NAME, DESCRIPTION) values
(1, 'VISUALIZAR_PERFIL', 'VISUALIZAR PERFIL'),
(2, 'EDITAR_PERFIL', 'EDITAR PERFIL');

INSERT INTO ROLES (ID, NAME, DESCRIPTION) VALUES
(1, 'ADMINISTRADOR', 'ADMINISTRADOR');

INSERT INTO ROL_PERMISSIONS(ID, ID_ROL, ID_PERMISSION) VALUES
(1, 1, 1),
(2, 1, 2);

INSERT INTO USERS (username, password, rol_id) VALUES
('danielchungara1@gmail.com', '$2a$12$qn5A3J1qxQlou7g/LEAIxu5e2yzfJ7R/HtBf/3BOSCsSTPZIH4/i6', 1);