CREATE TABLE RESET_PASSWORD
(
    USER_ID         BIGINT PRIMARY KEY UNIQUE,
    CODE       VARCHAR(255) NOT NULL,
    EXPIRATION DATETIME          NOT NULL
) ENGINE = INNODB;

ALTER TABLE RESET_PASSWORD
    ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID);