CREATE TABLE RESET_PASSWORD
(
    USER_ID    BIGSERIAL PRIMARY KEY,
    CODE       VARCHAR(255) NOT NULL,
    EXPIRATION TIMESTAMP          NOT NULL
);

ALTER TABLE RESET_PASSWORD
    ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID);