INSERT INTO permission(name, description)
values ('CREATE_CATEGORIES', 'CREATE CATEGORIES'),
       ('READ_CATEGORIES', 'READ CATEGORIES'),
       ('UPDATE_CATEGORIES', 'UPDATE CATEGORIES'),
       ('DELETE_CATEGORIES', 'DELETE CATEGORIES');
