INSERT INTO role_permission(role_id, permission_id)
VALUES ((select id from role where name = 'TESTER'), (select id from permission where name = 'CREATE_BRANDS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'CREATE_CATEGORIES')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'CREATE_PRODUCTS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'CREATE_ROLES')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'CREATE_USERS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'DELETE_BRANDS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'DELETE_CATEGORIES')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'DELETE_PRODUCTS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'DELETE_ROLES')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'DELETE_USERS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'READ_BRANDS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'READ_CATEGORIES')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'READ_PERMISSIONS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'READ_PRODUCTS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'READ_ROLES')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'READ_USERS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'UPDATE_BRANDS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'UPDATE_CATEGORIES')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'UPDATE_PRODUCTS')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'UPDATE_ROLES')),
       ((select id from role where name = 'TESTER'), (select id from permission where name = 'UPDATE_USERS'));